---
- name: Remove transparent proxy configuration from kernel settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
  become: yes
  loop:
    - { name: net.ipv4.ip_forward, value: '0' }
    - { name: net.ipv6.conf.all.forwarding, value: '0' }
    - { name: net.ipv4.conf.all.send_redirects, value: '1' }

- name: Disable iptables forwarding to mitmproxy
  ansible.builtin.iptables:
    ip_version: "{{ item }}"
    table: nat
    chain: PREROUTING
    flush: yes
  become: yes
  loop:
    - ipv4
    - ipv6
