- name: Install Vim and dependencies on Debian
  apt:
    name: [ build-essential, vim, cmake, python3-dev ]
    state: latest
  become: true
  when: ansible_os_family == 'Debian'
  tags:
    - skip_ansible_lint # Latest is fine

- name: Install Vim and dependencies on Arch
  pacman:
    name: [ vim, cmake ]
    state: latest
  become: true
  when: ansible_os_family == 'Archlinux'
  tags:
    - skip_ansible_lint # Latest is fine

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ vim_root }}"
    - "{{ vim_ftplugin }}"
    - "{{ vim_ftdetect }}"
    - "{{ vim_pack }}"
    - "{{ vim_undodir }}"

- name: Create the {{ vim_root }}/vimrc file
  template:
    src: 'templates/vimrc.j2'
    dest: "{{ vim_root }}/vimrc"

- name: Create the filetype detection files
  template:
    src: "{{ item }}"
    dest: "{{ vim_ftdetect }}/{{ item | basename | regex_replace('\\.j2', '') }}"
  with_fileglob:
    - "../templates/ftdetect/*"

- name: Create the filetype plugin files
  template:
    src: "{{ item }}"
    dest: "{{ vim_ftplugin }}/{{ item | basename | regex_replace('\\.j2', '') }}"
  with_fileglob:
    - "../templates/ftplugin/*"

- name: Install and update autoload plugins
  git:
    dest: "{{ vim_pack }}/start/{{ item.name }}"
    repo: "{{ item.repo }}"
    version: "{{ item.version }}"
    recursive: "{{ item.recursive }}"
  loop: "{{ vim_plugins }}"

